# SITE CONFIGURATION
baseurl: "https://clemy.nl/5a"
favicon: assets/favicon.ico # Icon displayed in the tab

reveal:
  title: "Boekbespreking - Mortina"
  transition: "none" # none/fade/slide/convex/concave/zoom
  theme: "raw" # black/beige/blood/league/moon/night/serif/simple/sky/solarized/white/raw
  number: true
  numberType: "c/t" # "h.v" / "h/v" / "c/t"

# Slides
collections:
  slides:
    output: true
    permalink: /:collection/:name
  basements:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea"]
